[package]
name = "myvtt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
hexx = { version = "0.23", features = ["serde"] }
indexmap = "2.12"
macroquad = "0.4"
ron = "0.12"
serde = { version = "1.0", features = ["derive"] }
